---

# Role defaults for contiv_network
# NOTE: Role defaults have a lower priority than inventory vars.
# Include variables which need to be overridden by inventory vars here.

contiv_network_mode: "standalone" # Accepted values: standalone, aci
netplugin_mode: "docker" # Accepted values: docker, kubernetes
fwd_mode: "bridge" #Accepted values: bridge , routing
ofnet_master_port: 9001
ofnet_agent_port1: 9002
ofnet_agent_port2: 9003
netmaster_port: 9999
gobgp_grpc_port: 8080
bgp_port: 179
vxlan_port: 4789
netplugin_rule_comment: "contiv network traffic"

contiv_network_version: "v0.1-06-14-2016.05-56-38.UTC"
contiv_network_tar_file: "netplugin-{{ contiv_network_version }}.tar.bz2"
contiv_network_src_file: "https://github.com/contiv/netplugin/releases/download/{{ contiv_network_version }}/{{ contiv_network_tar_file }}"
contiv_network_dest_file: "/tmp/{{ contiv_network_tar_file }}"

contivctl_version_no_v: "0.1-05-26-2016.22-31-22.UTC"
contivctl_version: "v{{ contivctl_version_no_v }}"
contivctl_tar_file: "{{ contivctl_version }}.tar.gz"
contivctl_src_file: "https://github.com/contiv/contivctl/archive/{{ contivctl_tar_file }}"
contivctl_dest_file: "/tmp/contivctl-{{ contivctl_tar_file }}"

apic_epg_bridge_domain: "not_specified"
apic_contracts_unrestricted_mode: "no"
