---
# Default values for docker role

docker_api_port: 2385
docker_version: 1.11.1
docker_compose_version: 1.8.0-rc1
docker_rule_comment: "docker api"
docker_device: ""
docker_device_size: "10000MB"
docker_device_metadata_size: "1000MB"
docker_cs_engine_supported_versions_ubuntu:
    "wily": [ "1.10", "1.11" ]
    "xenial": [ "1.11" ]
docker_mount_flags: "shared"
