---
- name: check for vagrant user
  shell: id vagrant
  register: vagrant_exist

- name: install bashrc with proxy configs
  template:
    src: bashrc.j2
    dest: /home/vagrant/.bashrc
    owner: vagrant
    group: vagrant
    mode: 0755
  when: vagrant_exist

- name: install bash_profile with swarm configs
  template:
    src: bash_profile.j2
    dest: /home/vagrant/.bash_profile
    owner: vagrant
    group: vagrant
    mode: 0755
  when: vagrant_exist
