---
# This role contains tasks for configuring and starting clusterm service

- name: copy shell script for starting collins
  template: src=collins.j2 dest=/usr/bin/collins.sh mode=u=rwx,g=rx,o=rx

- name: copy systemd units for collins
  copy: src=collins.service dest=/etc/systemd/system/collins.service

- name: start collins
  service: name=collins state=started

- name: download clusterm
  get_url:
    validate_certs: no
    url: https://github.com/contiv/cluster/releases/download/v0.0.0-01-05-2016.22-21-32.UTC/cluster-v0.0.0-01-05-2016.22-21-32.UTC.tar.bz2
    dest: /tmp/cluster-v0.0.0-01-05-2016.22-21-32.UTC.tar.bz2
    force: no

- name: install clusterm
  shell: tar vxjf /tmp/cluster-v0.0.0-01-05-2016.22-21-32.UTC.tar.bz2
  args:
    chdir: /usr/bin/
    creates: clusterm

- name: copy environment file for clusterm
  copy: src=clusterm dest=/etc/default/clusterm

- name: copy systemd units for clusterm
  copy: src=clusterm.service dest=/etc/systemd/system/clusterm.service

- name: start clusterm
  service: name=clusterm state=started
