---
# This role contains tasks for configuring and starting swarm service

- name: download swarm container image
  shell: docker pull swarm:{{ swarm_version }}
  tags:
    - prebake-for-dev

- name: copy the swarm start/stop script
  template: src=swarm.j2 dest=/usr/bin/swarm.sh mode=u=rwx,g=rx,o=rx

- name: copy systemd units for swarm
  copy: src=swarm.service dest=/etc/systemd/system/swarm.service

- name: start swarm
  service: name=swarm state=started

- name: setup iptables for swarm
  shell: >
      ( iptables -L INPUT | grep "{{ swarm_rule_comment }} ({{ item }})" ) || \
      iptables -I INPUT 1 -p tcp --dport {{ item }} -j ACCEPT -m comment --comment "{{ swarm_rule_comment }} ({{ item }})"
  become: true
  with_items:
    - "{{ swarm_api_port }}"
