---
# role variable for the kubernetes role
#
k8s_api_insecure_port: 8080
k8s_api_secure_port: 6443
k8s_image: "gcr.io/google_containers/hyperkube"
k8s_version: "v1.3.4"
k8s_rule_comment: "k8s traffic"
k8s_net_plugin_mode: "cni"
k8s_net_plugin_bin_dir: "/opt/cni/bin"
k8s_config_dir: "/etc/kubernetes"
k8s_cert_dir: "{{ k8s_config_dir }}/certs"
k8s_manifests_dir: "{{ k8s_config_dir }}/manifests"
k8s_net_plugin_config_dir: "{{ k8s_config_dir }}/cni/net.d"
k8s_local_cert_dir: "./certs"
