# These tasks are run when contiv_network_mode is set to aci

- name: pull aci-gw container
  shell: docker pull contiv/aci-gw

- name: copy shell script for starting aci-gw
  template: src=aci_gw.j2 dest=/usr/bin/aci_gw.sh mode=u=rwx,g=rx,o=rx

- name: copy systemd units for aci-gw
  copy: src=aci-gw.service dest=/etc/systemd/system/aci-gw.service

- name: start aci-gw container
  service: name=aci-gw state=started

- name: set aci mode
  shell: contivctl network global set --fabric-mode aci
