---
# This role contains tasks for installing ovs

- name: install openstack kilo repo (redhat)
  yum: "name=https://repos.fedorapeople.org/repos/openstack/openstack-kilo/rdo-release-kilo-1.noarch.rpm"
  when: ansible_os_family == "RedHat"
  tags:
    - prebake-for-dev

- name: install ovs (redhat)
  yum: name=openvswitch state=present
  when: ansible_os_family == "RedHat"
  tags:
    - prebake-for-dev

- name: download ovs binaries (debian)
  get_url:
    validate_certs: no
    dest: "{{ item.dest }}"
    url: "{{ item.url }}"
  with_items:
    - {
        url: "https://cisco.box.com/shared/static/v1dvgoboo5zgqrtn6tu27vxeqtdo2bdl.deb",
        dest: /tmp/ovs-common.deb
      }
    - {
        url: "https://cisco.box.com/shared/static/ymbuwvt2qprs4tquextw75b82hyaxwon.deb",
        dest: /tmp/ovs-switch.deb
      }
  when: ansible_os_family == "Debian"
  tags:
    - prebake-for-dev

- name: install ovs-common (debian)
  apt: "deb=/tmp/ovs-common.deb"
  when: ansible_os_family == "Debian"
  tags:
    - prebake-for-dev

- name: install ovs (debian)
  apt: "deb=/tmp/ovs-switch.deb"
  when: ansible_os_family == "Debian"
  tags:
    - prebake-for-dev

- name: start ovs service
  service: "name=openvswitch enabled=yes state=started"
  when: ansible_os_family == "RedHat"

- name: setup ovs
  shell: "ovs-vsctl set-manager {{ item }}"
  with_items:
    - "tcp:127.0.0.1:6640"
    - "ptcp:6640"
