---
# This role contains tasks for configuring and starting netmaster and netplugin service

- name: download netmaster and netplugin
  get_url:
    validate_certs: no
    url: https://github.com/contiv/netplugin/releases/download/v0.0.0-11-12-2015.00-55-50.UTC/netplugin-v0.0.0-11-12-2015.00-55-50.UTC.tar.bz2
    dest: /tmp/contivnet.tar.bz2

- name: install netmaster and netplugin
  shell: tar vxjf /tmp/contivnet.tar.bz2
  args:
    chdir: /usr/bin/
    creates: netmaster

- name: copy environment file for netmaster
  copy: src=netmaster dest=/etc/default/netmaster
  when: run_as == "master"

- name: copy systemd units for netmaster
  copy: src=netmaster.service dest=/etc/systemd/system/netmaster.service
  when: run_as == "master"

- name: start netmaster
  shell: systemctl daemon-reload && systemctl start netmaster
  when: run_as == "master"

- name: copy environment file for netplugin
  copy: src=netplugin dest=/etc/default/netplugin

- name: copy systemd units for netplugin
  copy: src=netplugin.service dest=/etc/systemd/system/netplugin.service

- name: start netplugin
  shell: systemctl daemon-reload && systemctl start netplugin

- name: setup netmaster host alias
  shell: echo "{{ service_vip }} netmaster" >> /etc/hosts

# XXX: need to move the following to correct roles
- name: install contivctl
  shell: source /etc/profile.d/00golang.sh && go get github.com/contiv/contivctl

- name: install docker-compose
  shell: pip install docker-compose

- name: install contiv-compose
  shell: >
     source /etc/profile.d/00golang.sh && \
     go get github.com/contiv/libcompose && \
     cd $GOPATH/src/github.com/contiv/libcompose && \
     make binary && \
     ln -s `pwd`/bundles/libcompose-cli_linux-amd64 $GOPATH/bin/contiv-compose
