---

# Role defaults for contiv_network
# NOTE: Role defaults have a lower priority than inventory vars.
# Include variables which need to be overridden by inventory vars here.

contiv_network_mode: "standalone" # Accepted values: standalone, aci
netplugin_mode: "docker" # Accepted values: docker, kubernetes
fwd_mode: "bridge" #Accepted values: bridge , routing

contiv_network_version: "v0.1-02-25-2016.09-29-08.UTC"
contiv_network_tar_file: "netplugin-{{ contiv_network_version }}.tar.bz2"
contiv_network_src_file: "https://github.com/contiv/netplugin/releases/download/{{ contiv_network_version }}/{{ contiv_network_tar_file }}"
contiv_network_dest_file: "/tmp/{{ contiv_network_tar_file }}"

contivctl_version: "v0.0.0-02-18-2016.22-10-53.UTC"
contivctl_tar_file: "contivctl-{{ contivctl_version }}.tar.bz2"
contivctl_src_file: "https://github.com/contiv/contivctl/releases/download/{{ contivctl_version }}/{{ contivctl_tar_file }}"
contivctl_dest_file: "/tmp/{{ contivctl_tar_file }}"
