- name: download consul binary
  get_url:
    validate_certs: no
    url: https://dl.bintray.com/mitchellh/consul/0.5.2_linux_amd64.zip
    dest: /tmp/consul.zip

- name: install consul
  shell: "chdir=/tmp creates=/usr/bin/consul unzip /tmp/consul.zip && mv /tmp/consul /usr/bin"

#NOTE: Upgrade pip to latest which is needed for correct installation of docker-compose
#XXX: This messes with the python packages already installed causing any yum/apt
#re-run to fail subsequently. We need a different way to update pip.
- name: upgrade pip
  pip:
    name: pip
    extra_args: "--upgrade"
