# install epel-release first to ensure the extra packages can be installed later
- name: install epel release package (redhat)
  yum:
    name: epel-release
    state: latest

- name: install/upgrade base packages (redhat)
  yum:
    name: "{{ item }}"
    update_cache: true
    state: latest
  with_items:
    - yum-utils
    - ntp
    - unzip
    - bzip2
    - curl
    - python-requests # XXX required by ceph repo, but it has a bad package on it
    - bash-completion
    - kernel #keep kernel up to date
    - libselinux-python
    - e2fsprogs
    - openssh-server

- name: install and start ntp
  service: name=ntpd state=started enabled=yes
