---
# Role defaults for ucp

ucp_version: "0.8.0"
ucp_local_dir: "fetch/ucp"
ucp_remote_dir: "/tmp"
ucp_instance_id_file: "ucp-instance-id"
ucp_fingerprint_file: "ucp-fingerprint"
ucp_fifo_file: "ucp-fifo"
ucp_bootstrap_node_addr: ""

ucp_admin_user: "admin"
ucp_admin_password: "orca"
ucp_controller_replica: "--replica"
