- name: Set Go version
  set_fact:
    go_version: "1.7"

- name: "download Golang {{ go_version }}"
  get_url:
    validate_certs: "{{ validate_certs }}"
    url: "https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"

- name: "install Golang {{ go_version }}"
  shell: "rm -rf go/ && tar xfvz /tmp/go{{ go_version }}.linux-amd64.tar.gz"
  args:
    chdir: /usr/local/

- name: setup golang environment
  copy:
    dest: /etc/profile.d/00golang.sh
    content: "export PATH=/opt/golang/bin:/usr/local/go/bin:$PATH; export GOPATH=/opt/golang"
